apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server3
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server3
  template:
    metadata:
      labels:
        role: nfs-server3
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /data
            name: nfs-pvc3
      volumes:
        - name: nfs-pvc3
          gcePersistentDisk:
            pdName: nfs-disk3
            fsType: ext4
